AppSensorsHomeAssistant/Models/ErrorViewModel.cs
namespace AppSensorsHomeAssistant.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppSensorsHomeAssistant/Models/Sensor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppSensorsHomeAssistant.Models
{
    [Table("states_meta")]
    public class Sensor
    {
        [Key]
        [Column("metadata_id")]
        public int IdSensor { get; set; }
        [Column("entity_id")]
        public string Entidad { get; set; }
    }
}

AppSensorsHomeAssistant/Models/SensorState.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppSensorsHomeAssistant.Models
{
    [Table("v_states_sensors")]
    public class SensorState
    {
        [Key]
        [Column("state_id")]
        public int IdState { get; set; }
        [Column("metadata_id")]
        public int IdMetaData { get; set; }
        [Column("entity_id")]
        public string Entidad { get; set; } = null!;
        [Column("state")]
        public string Estado { get; set; } = null!;
        [Column("shared_attrs")]
        public string Atributos { get; set; } = null!;

    }
}

AppSensorsHomeAssistant/Controllers/HomeController.cs
using AppSensorsHomeAssistant.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppSensorsHomeAssistant.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppSensorsHomeAssistant/Controllers/SensorsController.cs
using AppSensorsHomeAssistant.Models;
using AppSensorsHomeAssistant.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AppSensorsHomeAssistant.Controllers
{
    public class SensorsController : Controller
    {
        private RepositoryHomeAssistant repo;

        public SensorsController(RepositoryHomeAssistant repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> MisSensores()
        {
            List<Sensor> sensores = await this.repo.GetSensorsAsync();
            return View(sensores);
        }

        public async Task<IActionResult> Index()
        {
            List<SensorState> sensoresStates = await this.repo.GetSensorStatesAsync();
            return View(sensoresStates);
        }

        public async Task<IActionResult> SearchSensorState(int id)
        {
            List<SensorState> sensoresStates = await this.repo.GetSensorStatesAsync(id);
            return View(sensoresStates);
        }
    }
}

AppSensorsHomeAssistant/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppSensorsHomeAssistant/Views/Sensors/Index.cshtml
@model IEnumerable<AppSensorsHomeAssistant.Models.SensorState>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdState)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdMetaData)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Entidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Atributos)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdState)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdMetaData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Entidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Atributos)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AppSensorsHomeAssistant/Views/Sensors/MisSensores.cshtml
@model IEnumerable<AppSensorsHomeAssistant.Models.Sensor>

@{
    ViewData["Title"] = "MisSensores";
}

<h1>MisSensores</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSensor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Entidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSensor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Entidad)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

AppSensorsHomeAssistant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppSensorsHomeAssistant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppSensorsHomeAssistant.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppSensorsHomeAssistant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                            asp-controller="Sensors" asp-action="MisSensores">Sensores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppSensorsHomeAssistant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>